flag_management:
  default_rules: # the rules that will be followed for any flag added, generally
    carryforward: true
    statuses:
      - type: project
        target: auto
        threshold: 1%
      - type: patch
        target: 90%
  individual_flags: # exceptions to the default rules above, stated flag by flag
    - name: pgscatalog.downloadapp  #fill in your own flag name
      paths: 
      - pgscatalog.downloadapp
      carryforward: true
      statuses:
        - type: project
          target: 20%
        - type: patch
          target: 100%
