name: Run pytest on pgscatalog.calc

on:
  push:
    paths:
      - 'pgscatalog.calc/**.py'
  pull_request:
    paths:
      - 'pgscatalog.calc/**.py'

jobs:
  pytest-calc:
    uses: ./.github/workflows/pytest.yaml
    with:
      package-directory: "pgscatalog.calc"