name: Run pytest on pgscatalog.core

on:
  push:
    paths:
      - 'pgscatalog.core/**.py'
  pull_request:
    paths:
      - 'pgscatalog.core/**.py'

jobs:
  pytest-core:
    uses: ./.github/workflows/pytest.yaml
    with:
      package-directory: "pgscatalog.core"