name: Run pytest on pgscatalog.match

on:
  push:
    paths:
      - 'pgscatalog.match/**.py'
  pull_request:
    paths:
      - 'pgscatalog.match/**.py'

jobs:
  pytest-match:
    uses: ./.github/workflows/pytest.yaml
    with:
      package-directory: "pgscatalog.match"